# User settings for data files and gene label

#  MGA
Nucleotide: MGA_refseq_transcript.fasta
Protein: MGA_refseq_protein.fasta
CSV: MGA_orthologs.csv
Label: PrimateMGA

# User settings for NCBI Entrez
Email: "agl4001@med.cornell.edu"






